### ISSUE TITLE
Incorrect error in `Credentials.handle` L118

### ISSUE THREAD

**Issue by youming-lin** [IBM-Swift/Kitura-Credentials#45]
Sample code: https://gist.github.com/jarrodparkes/be7c4c32dcae18bd0e46639576c918a1

Compile and run app. Execute `curl -v localhost:8090/secure`. Immediately, server process prints out this error:
```
[2017-04-12T14:56:10.005-05:00] [ERROR] [Credentials.swift:118 handle(request:response:next:)] The authentication failed either because the authentication data was not recognized by any non-redirecting plugin, or because a session, required by redirecting authentication, was not configured.
```
The error message is logged [here](https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift#L117). The code correctly returns a 401 unauthorized status code (as seen in the verbose output of the `curl` command), but the error message should not be logged; see [`onFailure`](https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift#L94) for the correct behavior.

Raised in Slack: https://swift-at-ibm.slack.com/archives/C29BLC4KB/p1492024563611004

**Comment by irar2** [comment]
The problem is that at that point in the code we can't know what exactly happened, hence the long and somewhat vague error message. 

To fix this we can add an optional parameter to onPass and onFailure methods, and pass concrete error messages back to Credentials. 

We can put the error message in the response's body in case of onFailure (and also print it with Log.verbose).

We will collect all the onPass error messages.  
If we get [here](https://github.com/IBM-Swift/Kitura-Credentials/blob/master/Sources/Credentials/Credentials.swift#L117) we will print all the messages using Log.warning (explaining why each non-redirecting plugin passed).  In addition, for every existing redirecting plugin, we will print a warning that a session was not configured.

@youming-lin Does this solve the problem in your opinion?

**Comment by youming-lin** [comment]
I think we can tweak the `if` condition to clarify that, if there is no redirecting plugins registered and there exist at least one non-redirecting plugin, then we return 401 Unauthorized.

`authentication data was not recognized by any non-redirecting plugin` is the same as receiving incorrect credentials; therefore, I don't think it's necessary to log an error stating this.

Here is my thought:
1. if no session, no non-redirecting plugin, AND at least one redirecting plugin, log the `a session, required by redirecting authentication, was not configured` error message
2. otherwise, return 401 Unauthorized.

**Comment by irar2** [comment]
OK, we can do this.
