### ISSUE TITLE
(Question)How do i prevent a user login twice and more?

### ISSUE THREAD

**Issue by diuming** [IBM-Swift/Kitura-Credentials#81]
HI,
How do i prevent a user login twice and more. 
it means the user can be logined once in any hosts or any browsers(a host more than one browsers), except the user logout.
`I don't have any experience on server side credentials and session.`

I refer to `Local authentication` but I don't have any ideas for that.
which one is correct start point? Kitura-Credentials or Kitura-Session
Could you give me advice?
thanks

**Comment by Andrew-Lees11** [comment]
@diuming 
Can you provide some more details about what you are trying to do? 
Are you creating a rest backend or a web application?

I recommend you use CredentialsLocal 1.0.0 since that is still set up as a "Redirecting plugin"
Credentials local should have a login route that takes a username and password from the body of the request (E.g. sent via a POST form), authenticates the user and then keeps them logged in via a session. 

When you say you want to prevent a user logging in twice i assume you mean that you don't want a user to be able to be logged in on two machines. 

You could implement this for a web application on your login route. If you store the UserID with the sessionID when a user logs in, when a user next logs in you could check if they are already logged in with a different session ID and if true remove that session from the session store. This would log out somebody from a different machine.

**Comment by diuming** [comment]
@Andrew-Lees11 thank you for replying

As per your advice, I implemented `CredentialsLocal 1.0.0`. It works very well.
I stored  UserID with the session `request.session?["userID"] = "specific value"`.
But the request have only one session. 
How do I check `different session`?
do I need to create a class to store them(session, specific value...)?

thanks

**Comment by Andrew-Lees11** [comment]
Yes you are going to have to implement your own middleware to check and delete sessions. I have made some example code below for how you could implement this:
```swift
// Inside App

// For demo purpose, Session should be stores using a redis/Database store
    static let store = InMemoryStore()
    // For demo purposes. User to session map should be stored in a database.
    static var userSessionDictionary = [String: String]()
    let session = Session(secret: "secret", cookie: [CookieParameter.name("KituraAuthCookie")], store: App.store)
    let oneSessionAuth = OneSessionAuthenticated()

// Inside postInit()
router.all(middleware: session)
router.all(middleware: oneSessionAuth)

// Inside their own files
struct OneSessionAuthenticated: RouterMiddleware {
    func handle(request: RouterRequest, response: RouterResponse, next: @escaping () -> Void) throws {
        guard let userId = request.userProfile?.id, let session = request.session else {
            return try response.send(status: .unauthorized).end()
        }
        if let loggedInSessionId = App.userSessionDictionary[userId] {
            if loggedInSessionId != session.id {
                // Delete session from store logging out the other user
                App.store.delete(sessionId: loggedInSessionId) { (_) in }
            }
        }
        App.userSessionDictionary[userId] = session.id
        next()
    }
}

class InMemoryStore: Store {
    
    private var store = [String: Data]()
    
    internal func load(sessionId: String, callback: @escaping (Data?, NSError?) -> Void) {
        callback(store[sessionId], nil)
    }
    
    internal func save(sessionId: String, data: Data, callback: @escaping (NSError?) -> Void) {
        store[sessionId] = data
        callback(nil)
    }
    
    internal func touch(sessionId: String, callback: @escaping (NSError?) -> Void) {
        callback(nil)
    }
    
    internal func delete(sessionId: String, callback: @escaping (NSError?) -> Void) {
        store.removeValue(forKey: sessionId)
        callback(nil)
    }
}
```

**Comment by diuming** [comment]
@Andrew-Lees11 thank you for helping me.
I got it.
thanks
